### ISSUE TITLE
solutionFname

### ISSUE THREAD

**Issue by zhaishengfu** [eldar/deepcut#1]
@eldar 
hello, i am interested in your work of multiperson. here i met one problem in **test_apatial_app_neighhbour.m:** in line 453
**unLab = marray_load(solutionFname, dataName);**
and i find that the solutionFname desn't exit. i see your code and find that you really don't save solutionFname. i think something is missing or the code has some bug.Do you think so?

**Comment by eldar** [comment]
This is not a bug, because the file solutionFname is generated by running the solver. The call is at line 441, basically it runs an external executable that reads the problem files and runs the inference to produce the solution. You can find it in the instructions on how to build the solver. Another issue might be that Gurobi license is not properly configured, hence the solver cannot run. Sorry for the inconvenience.
